# Generated by Django 5.1.4 on 2024-12-08 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_employeeform_delete_employeemanagement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeform',
            name='name',
        ),
        migrations.AlterField(
            model_name='employeeform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
