# Generated by Django 5.1.4 on 2024-12-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_employeeform_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeform',
            name='dynamic_fields',
            field=models.JSONField(),
        ),
    ]
