# Generated by Django 5.1.4 on 2024-12-08 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_employeeform_dynamic_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_data', models.JSONField(default=dict)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='management.employeeform')),
            ],
        ),
    ]
