# Generated by Django 5.1.4 on 2024-12-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_employeemanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagement',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='management.employeeform'),
        ),
    ]
