# Generated by Django 5.1.4 on 2024-12-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_employeemanagement_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagement',
            name='dynamic_data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
