# Generated by Django 5.1.4 on 2024-12-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_employeemanagement_dynamic_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeform',
            name='dynamic_fields',
            field=models.JSONField(null=True),
        ),
    ]
